### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by codeguy** [pmjones/adr#10]
Some quick feedback.
- ADR seems like it represents the simplification and specialization of web app development much like the shift from monolithic frameworks to smaller, more nimble microframework architectures. And just like frameworks <--> microframeworks, ADR is not a panacea, but more a "right tool for the job" kind of thing. Frameworks are still useful, but sometimes a micro-framework is all you need. Don't overengineer an MVC solution when a simpler ADR architecture will suffice. As you said, this seems to better represent what we developers are doing on a daily basis as we target smaller, more specific tasks.
- Letting the HTTP response become the View is a more appropriate depiction of the modern, API-driven web application.

I would like to see more clarification on this point:

> The Action interacts with the Domain in the same way a Controller interacts with a Model, but does not interact with a View or template system. It sets data on the Responder and hands over control to it.

Slim uses a View class to generate output that the Action/Controller sends to the Responder/Response. For Slim, the Responder is very much a wrapper around an HTTP response. It is not required to use a View with Slim, but it does help implement third-party templating systems to help generate the responder/response body. Could this responsibility be merged into the Responder? Perhaps, but I feel like that would violate separation of concerns and make the Responder overcomplicated. Or maybe your concept of a "responder" is more a sub-system/group of components and not a single component? Or maybe we should not liken templating systems with the term "View"?

**Comment by AucT** [comment]
Just coming across a lot of scripts and simple frameworks...
Since what year 90% of scripts don't show working demo? It's really annoying... 4 of 5 frameworks or scripts are bugged or just doesn't provide anything for beginners. I think the it community hates people and don't want new IT people...
