### ISSUE TITLE
Storing application state in actions is not a good idea

### ISSUE THREAD

**Issue by TRPB** [pmjones/adr#25]
A fundamental problem I can see with this approach (or at least your examples) is, like the pseudo-MVC implementations, there is nowhere that treats application state as its own concern and very tightly couples it to the action. In effect, the action is encapsulating the application state. 

I've written extensively about why a controller as a mediator (that is, feeding data from the model to the view) is a bad idea. This implementation still contains that fundamental design flaw that exists in most "MVC" implementations and as such the same level of limited flexibility.

See my post here: https://r.je/views-are-not-templates.html

Moving that to an action does not help solve the underlying issue with pseudo-MVC. Consider the following example code using MVC, I'm struggling to see how I can achieve the same level of flexibility with ADR without a lot of repeated code, using inheritance (which is always a bad idea anyway) or doing something that feels hacky like having actions create other actions.

A table with a list of products in an admin area:

```
[SEARCH-input]
ID    | Title 
001 | Tea | Edit | Delete
002 | Coffee | Edit | Delete

Page [1] [2] [3]
```

Here, there are 5 potential actions:

1) Sort the table by clicking on column headers
2) Search for products by entering something in the search box
3) Edit a product
4) Delete a product
5) Switch page

All but one of these actions will just change the results in the table that's being displayed.. they all require the same view. Editing the product requires a different view.

``` php
//Model
class ProductsModel {
    public $searchCriteria = ['deleted = 0'];
    public $sortOrder = 'id DESC';
    public $page = 1;

    const PRODUCTS_PER_PAGE = 5;

    public function getProducts() {
        //Yes, SQL injectionalble... demo purposes only
        return $this->db->query('SELECT * FROM products WHERE  ' . implode('AND', $this->searchCriteria) . ' ORDER BY ' . $this->sortOrder . ' LIMIT ' . self::PRODUCTS_PER_PAGE . ' OFFSET ' . ($this->page-1*self::PRODUCTS_PER_PAGE));
    }   


    public function delete($id) {
        $this->db->query('UPDATE products SET deleted = 1 WHERE id = ' . $id);
    }
}



//Controller
class ProductListController {
    private $products;

    public function __construct(ProductsModel $products) {      
        $this->products = $products;    
    }

    public function search($name) {
        $this->products->searchCriteria[] = 'name = ' . $name;  
    }

    public function delete($id) {
        $this->products->delete($id);
    }

    public function page($num) {
        $this->products->page = 1;
    }

    public function sort($columnName, $dir) {
        $this->products->sortOrder = $columnName . ' ' . $dir;
    }
}
```

The view would then call getProducts() on the ProductsModel instance and list all the required products. (N.b. the view would work out the pagination as it's display logic)

Here I can have a router call one or more of the controller actions to chain them together and use sorted, paginated, searched results. With ADR and having the $this->view->setData() call, this isn't possible to chain the actions and affect the state of the model, because the application state is stored inside the action (The action is holding the "Current set" of records beind displayed)

Not only that, the amount of code required by each action is incredibly excessive compared with a proper MVC implementation where most controller actions just alter the model's state. The reason for that is poor separation of concerns. Your action in the BlogCreateAction has several different concerns: 
- The state of the application 
- Informing the responder the state
- Taking user input
- Fetching data from the domain into the application

This is a very inflexible approach as it essentially takes the Model and Controller and bundles them together in a single "action" heavily reducing re usability of the various concerns. 

By tightly coupling application state to user input you heavily reduce the flexibility and reusability of the code. To have a sorted, paginated table as above I need a separate action for each BlogListSortedAndPaginated, BlogListSortedPaginatedAndFiltered which gets very messy. Not only that, because these are concrete classes, inheritance cannot be used to resolve some of these issues because you'll very quickly run into the diamond problem even if you could somehow share application state between the actions.

The problem this creates is that the code in the controller is not reusable. To re-use the responder with a different action, a lot of that code has to be recreated. In MVC I can swap out the controller (e.g. one that set a specific state on the model) without having to re-code the model or the view. I can re-use the same model and view with that substituted controller. Alternatively, I can substitute the view to display the same filtered/sorted/whatever data set in a different way. If I want to substitute the view, it must have the API that the responder is hoping for because the action is coupled to the responder and breaks encapsulation by doing so. The action needs to know exactly what variables are available on the responder:  $this->responder->setData(array('blog' => $blog)); the action can only be used with a responder that is expecting a 'blog' variable to be set. Why does the action need to know anything about the implementation of the responder?

If I want to use a different responder I must make sure there is a 'blog' variable available. Whereas with MVC proper, the View has a contract with the model. If I want to I can sawp out both the View and the Model while reusing the controller. There may or may not be a "getProducts()" method on the model but the controller doesn't care. By making interfaces to handle the view/model contract I can use any model with the view as long as it follows the interface. Consider the following interface:

``` php
interface Listable {
    public function getResults();
    public function getFields();
}
```

I could use this in a View to draw both the rows and columns for any given model. As long as my model implemented the interface I could create a table of products/blogs/users/whatever and it could all use the same view. Whether or not I'm doing this should be entirely irrelevant to the controller.

In ADR this is not possible because the action and the responder are coupled because there is no concern for the application state (The M in MVC).

**Comment by pmjones** [comment]
I'll leave a longer response (heh) at some point in the future, but I want to address some interrelated points on which we agree.

> Your action in the BlogCreateAction has several different concerns:

...

> This is a very inflexible approach as it essentially takes the Model and Controller and bundles them together in a single "action" heavily reducing re usability of the various concerns.

...

> the code in the controller is not reusable.

And so on.

I completely agree with you on that related set of points. My only response is that the example code in the paper is as a *transitional* example, to show that response-building work should be extracted from the action entirely. The ending-state action code is otherwise very similar to the beginning-state controller code, to make comparison easier for the reader. In a finalized version, all of that application-related code would be extracted to the domain layer, not left in the action.

I get that you don't like the idea of action-as-mediator, so the following may still be unsatisfying to you, but I would expect a more-proper (if not fully perfected) end-state would look more like this: https://github.com/pmjones/adr/blob/master/example-code/Web/Blog/Action/BlogCreateAction.php

**Comment by pmjones** [comment]
And on further re-reading of the paper, I realize that I say as much ... 

> Again, we can see numerous refactoring opportunities here, especially in the domain model work. The point is that the Action does not perform any Responder work at all. That work is handled entirely by the Responder logic.

... but I get that it might be easy to overlook that.
