### ISSUE TITLE
Use __invoke() like it's meant to be used

### ISSUE THREAD

**Issue by franz-josef-kaiser** [pmjones/adr#37]
In your article/ post you write

    $this->responder->__invoke();

Please, just use `$this->responder()`. The `__invoke()` method works pretty much like `__toString()` where you could `echo $this->responder` and the magic method would get called.

**Comment by pmjones** [comment]
Wish I could. If you do `$this->responder()` then PHP interprets that as "the responder() method on $this object". The only other alternative would be to do `$responder = $this->responder; return $responder();`.
