### ISSUE TITLE
Question in regards to Responder and PSR-7

### ISSUE THREAD

**Issue by potherca** [pmjones/adr#41]
I'd be quite interested to learn your views on ADR in regards to the [PSR-7](http://www.php-fig.org/psr/psr-7/) Request/Response Interfaces.

This seems the domain of the Responder but does it change/influence the mechanism outlined in your paper? 

I am aware that
> To stay in line with precedent, this pattern omits the incoming HTTP request.

but it would also be interesting to outline how the two (ARD & PSR-7) interact.

**Comment by pmjones** [comment]
Lucky for you there are two reference projects!

The first is from me, called Radar. The [Radar.Project](https://github.com/radarphp/Radar.Project) package is a system skeleton, which uses the core [Radar.Adr](https://github.com/radarphp/Radar.Project) library underneath. The second is from @shadowhand, called [Equip](https://github.com/equip/framework).

They both use some of the same underlying libraries, like Relay and Arbiter and Diactoros, but differ in other respects, such as choice of DI and router systems. Examining either or both of them should help show how PSR-7 works very naturally with ADR implementations.

I hope that begins to help; please let me know if it does not.

**Comment by potherca** [comment]
Thanks for the references! Studying them both as we speak.
