### ISSUE TITLE
Cache validation

### ISSUE THREAD

**Issue by MatTheCat** [pmjones/adr#44]
If the responder is in charge of building the response from the return of an action how do you handle returning a 304? It should be happening before the end of the action but it still would be a response.

**Comment by MatTheCat** [comment]
I fail to see how this is related? You could store in apcu the time the last subresource has been modified eg.

**Comment by pmjones** [comment]
> I fail to see how this is related?

Stick with me. :-)

>  You could store in apcu the time the last subresource has been modified eg.

Sure -- you touch a form of storage. Or, if you don't happen to have APCU or memcache or something else, you would read a little bit from the database to see if the resource had been modified.

So *then* the question becomes: why is your **user interface** layer (the part that reads input from a request, and writes output to a response) touching storage at all? It's user-interface, not infrastructure or domain.

One of the rules-of-thumb in ADR is: "if it touches storage, it probably goes in the Domain."

And that's the answer here. Your action would pass along the "has it changed?" headers to the domain.  The domain would use those as part of its work to return a payload; if the resource had not changed, the payload might be empty with a status of "NOT_MODIFIED". The action would then pass the payload to a responder; if the status was NOT_MODIFIED, it would sends back a 304.

**Comment by MatTheCat** [comment]
Oh okay I see the point. So it's no problem the domain knows all of the resources needed to generate a response?

**Comment by pmjones** [comment]
> So it's no problem the domain knows all of the resources needed to generate a response?

Correct. The Domain is what interacts with all the infrastructure bits, maybe in a DDD sort of way, or maybe in some other way. (As a side note, it's not so much "needed to generate a response" as "needed to deliver a result/payload back to the action" -- but that might be nitpicking. ;-)

**Comment by MatTheCat** [comment]
Yep thanks I'll try implementing this!
