### ISSUE TITLE
Pre-domain input munging

### ISSUE THREAD

**Issue by cxj** [pmjones/adr#45]
What's a clean way to do the following.

My Radar/Adr Actions are presently all direct calls to my Domain classes, e.g.:

```php
$adr->get(ListClaims::CLASS, '/list-claims', App\ListClaims::CLASS);

$adr->get('/ping', '/ping', App\Ping::CLASS)->responder(JsonResponder::class);
```

This has worked fine so far, as all input value checking and manipulation (e.g. range limits) have been appropriate at the Domain level.  That is, all callers of the Domain, whether HTTP or CLI or what-have-you, do not care.

Now, however, I've run into a situation where _only_ HTTP callers of the Domain _do care_.  This is because of bandwidth and memory limitations only web browser connections have.  I want to range limit my input to prevent a user from asking for 1 million rows in a table, for instance.  The Domain should not need to know or care about that.

But only specific routes in my Radar/Adr dispatcher need that kind of control.

Is the correct thing to create an Action class that clearly belongs to the HTTP-aware side, manipulate the values there, and then call my Domain application service, (normally called directly from the dispatcher)?

Or is this a job for middleware, since the bandwidth/output size limits are general for all HTTP requests?  But this seems to mix awareness of specific Actions inputs with the general data stream.

**Comment by pmjones** [comment]
> Is the correct thing to create an Action class that clearly belongs to the HTTP-aware side, manipulate the values there, and then call my Domain application service, (normally called directly from the dispatcher)?

I'd say this is the right thing to do.

You're using Radar, which allows you to specify an Input handler on the route (via the Arbiter library, which acts as a standardized Action). So, you should be able to do something like this:

```php
$adr->get(...)
    ->input(function ($request) {
        // cf. EGPCS, where Files is part of Post,
        // and Attributes is part of Server
        $input = [
            array_replace(
                (array) $request->getQueryParams(),
                (array) $request->getParsedBody(),
                (array) $request->getUploadedFiles(),
                (array) $request->getCookieParams(),
                (array) $request->getAttributes()
            )
        ];

        // modify $input elements as you wish
        // ...

        // return the input array
        return $input;
    });
```

Does that help?

**Comment by pmjones** [comment]
Alternatively, instead of doing manipulation of the input elements (with the various conditionals that are likely to be there), you can *add to* the input array, sending something like a flag to the Domain telling it "you need to apply greater restrictions in this case".

**Comment by pmjones** [comment]
See also https://github.com/radarphp/Radar.Project/blob/1.x/docs/routing.md#manually-specifying-a-custom-input-class

**Comment by cxj** [comment]
Hi Paul.  Thanks for the 3(!) responses, and suggested solutions.  I'll take a look and see what makes the best sense for my situation.  It looks like it should be pretty easy to keep my concerns separated, which is what I love about Radar.
