### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by isrd1** [pmjones/adr#48]
Is there any chance of providing an example front-controller for a few obvious use cases, with perhaps an sql script too?  This would mean one could clone the repo and actually run, test and debug it.  Personally, I find it so much easier to understand the control flows if I can follow it with a ide debugger.

**Comment by ElForastero** [comment]
I don't see any difficulties in implementing a front controller. The ADR isn't about this. Please correct me if I'm wrong.

You'll, anyway, need a router component and a convention about URI, which may differ from project to project.

**Comment by isrd1** [comment]
Hello ElForastero,  I didn't the ADR was about a front-controller, that's precisely why I'm asking if there is one, with appropriate other connections, such that the project can be extracted and run easily.

The reason I ask is that I'm not familiar with the aura components included in the composer package and it'd save a lot of time, therefore, and allow me, and others I imagine, to actually get the code working for evaluation.

Perhaps, if you don't see any difficulties in implementing a front controller you might post one, with appropriate code about your router and URI conventions, for the project at hand that is, blogs.

Regards, Rob

**Comment by pmjones** [comment]
Hi @isrd1 -- You should be able to use an ADR Action with any existing router that points to a webbish-MVC controller.  For example, if an MVC router does this ...

```php
// on POST to the path /foo/bar, instantiate BazController
// and call the dibAction method
$router->post('/foo/bar', 'BazController', 'dibAction');
```

... then you should be able to do this with a callable Action class:

```php
$router->post('/foo/bar/baz', 'BazDibAction', '__invoke');
```

Does that help?

**Comment by isrd1** [comment]
I'll try that out, thank you very much for the pointer.
