### ISSUE TITLE
Difference between an Action and an Application Service?

### ISSUE THREAD

**Issue by notflip** [pmjones/adr#64]
I'm reading a lot about the design methods proposed here, and I absolutely love it!

However I'm not sure I understand correctly what the difference is between an Application Service and an Action, or are they similar?

**Comment by pmjones** [comment]
Hi @notflip -- Thanks for saying!

The Action and the Application Service are very different things. An "Application Service" is an entry point to the Domain, and should be considered Domain layer logic. The Action is User Interface logic; all it does is take input from the HTTP request, pass it into the Domain (the Application Service in this case), and then get back the result from the Domain logic. The Action is very boring; the Domain is where all the "real" work happens.

In this example ... <https://paul-m-jones.com/post/2015/08/09/service-classes-payloads-and-responders/> ... the OrdersService would be a stand-in for an Application Service. Notice how the Action does very little work, and the Domain does all the heavy lifting.

Does that begin to help?
