### ISSUE TITLE
Where to put Transformers in ADR?

### ISSUE THREAD

**Issue by odan** [pmjones/adr#66]
A Transformer provides a presentation and transformation layer for complex data output, the like in RESTful APIs.
Transformers contain the business logic for changing a data format to whatever you need for the output, for exmaple JSON. 
To goal is to create a “barrier” between source data and output, so schema changes do not affect users.

For example [Fractal](https://fractal.thephpleague.com/) is such a component that is able to transform the input data into a representation for the Response.

I am thinking about where a Transformer would be placed from the ADR point of view. According to the [IPO model](https://en.wikipedia.org/wiki/IPO_model), the transformer should be in the domain, because it processes and generates data. So the result of an Application-Service would have to be the result of the Transformer because this data was prepared use-case specific within the Application-Service.

On the other hand, a Transformer puts the data into the right "form" for the presentation (view). The preparation of the view-specific structure would also be the task of the Responder. We already know this from HTML, where ViewData is inserted into the corresponding HTML template.

So my question is: Does a Transformer belongs to the Domain or the Responder?

**Comment by pmjones** [comment]
My intuition is that, as presentation logic, it would best be part of a Responder.

As far as the Use Case (or Application Service, etc) is concerned, the idea is that it is separated from any particular kind of user interface; it doesn't care if the presentation is JSON, HTML, CSV, XML, whatever. It just returns Domain results or Domain objects, likely wrapped in a Domain Payload. If a Use Case gets into the business of transforming those results *for presentation purposes* it is overstepping its bounds.

Does that begin to help?

**Comment by odan** [comment]
Hi @pmjones :-)

Yes that helps me a lot. Thank you very much!
